services:
    openssh-server:
        image: lscr.io/linuxserver/openssh-server:latest
        container_name: openssh-server
        hostname: openssh-server #optional
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - SUDO_ACCESS=true #optional
            - PASSWORD_ACCESS=true #optional
            - USER_PASSWORD=admin #optional
            - USER_NAME=admin #optional
        volumes:
            - ./testDir/config:/config
            - ./testDir/dst:/tmp
        ports:
            - 2222:2222
        restart: unless-stopped